; Supervisor Configuration
[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/sbin/php-fpm8.2 -F

[program:reverb]
command=php artisan reverb:serve
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/reverb.err.log
stdout_logfile=/var/log/supervisor/reverb.out.log

; Laravel Queues
[program:queue]
command=php artisan queue:work --tries=3
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/queue.err.log
stdout_logfile=/var/log/supervisor/queue.out.log